In [1]:
import pandas as pd

In [3]:
data=pd.read_csv("student_habits_performance.csv")
data

,student_id,age,gender,study_hours_per_day,social_media_hours,netflix_hours,part_time_job,attendance_percentage,sleep_hours,diet_quality,exercise_frequency,parental_education_level,internet_quality,mental_health_rating,extracurricular_participation,exam_score
0,S1000,23,Female,0.0,1.2,1.1,No,85.0,8.0,Fair,6,Master,Average,8,Yes,56.2
1,S1001,20,Female,6.9,2.8,2.3,No,97.3,4.6,Good,6,High School,Average,8,No,100.0
2,S1002,21,Male,1.4,3.1,1.3,No,94.8,8.0,Poor,1,High School,Poor,1,No,34.3
3,S1003,23,Female,1.0,3.9,1.0,No,71.0,9.2,Poor,4,Master,Good,1,Yes,26.8
4,S1004,19,Female,5.0,4.4,0.5,No,90.9,4.9,Fair,3,Master,Good,1,No,66.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,S1995,21,Female,2.6,0.5,1.6,No,77.0,7.5,Fair,2,High School,Good,6,Yes,76.1
996,S1996,17,Female,2.9,1.0,2.4,Yes,86.0,6.8,Poor,1,High School,Average,6,Yes,65.9
997,S1997,20,Male,3.0,2.6,1.3,No,61.9,6.5,Good,5,Bachelor,Good,9,Yes,64.4
998,S1998,24,Male,5.4,4.1,1.1,Yes,100.0,7.6,Fair,0,Bachelor,Average,1,No,69.7
999,S1999,19,Female,4.3,2.9,1.9,No,89.4,7.1,Good,2,Bachelor,Average,8,No,74.9

In [6]:
data.isnull().sum()

student_id                        0
age                               0
gender                            0
study_hours_per_day               0
social_media_hours                0
netflix_hours                     0
part_time_job                     0
attendance_percentage             0
sleep_hours                       0
diet_quality                      0
exercise_frequency                0
parental_education_level         91
internet_quality                  0
mental_health_rating              0
extracurricular_participation     0
exam_score                        0
dtype: int64

In [7]:
data["parental_education_level"].fillna("Unknown",inplace=True) 
data.isnull().sum()

C:\Users\mayan\AppData\Local\Temp\ipykernel_24684\3291950918.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["parental_education_level"].fillna("Unknown",inplace=True)

student_id                       0
age                              0
gender                           0
study_hours_per_day              0
social_media_hours               0
netflix_hours                    0
part_time_job                    0
attendance_percentage            0
sleep_hours                      0
diet_quality                     0
exercise_frequency               0
parental_education_level         0
internet_quality                 0
mental_health_rating             0
extracurricular_participation    0
exam_score                       0
dtype: int64

In [10]:
data=pd.get_dummies(
    data,
    columns=["gender","part_time_job","diet_quality","parental_education_level","internet_quality","extracurricular_participation"],
    drop_first=True
)

In [11]:
data

,student_id,age,study_hours_per_day,social_media_hours,netflix_hours,attendance_percentage,sleep_hours,exercise_frequency,mental_health_rating,exam_score,...,gender_Other,part_time_job_Yes,diet_quality_Good,diet_quality_Poor,parental_education_level_High School,parental_education_level_Master,parental_education_level_Unknown,internet_quality_Good,internet_quality_Poor,extracurricular_participation_Yes
0,S1000,23,0.0,1.2,1.1,85.0,8.0,6,8,56.2,...,False,False,False,False,False,True,False,False,False,True
1,S1001,20,6.9,2.8,2.3,97.3,4.6,6,8,100.0,...,False,False,True,False,True,False,False,False,False,False
2,S1002,21,1.4,3.1,1.3,94.8,8.0,1,1,34.3,...,False,False,False,True,True,False,False,False,True,False
3,S1003,23,1.0,3.9,1.0,71.0,9.2,4,1,26.8,...,False,False,False,True,False,True,False,True,False,True
4,S1004,19,5.0,4.4,0.5,90.9,4.9,3,1,66.4,...,False,False,False,False,False,True,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,S1995,21,2.6,0.5,1.6,77.0,7.5,2,6,76.1,...,False,False,False,False,True,False,False,True,False,True
996,S1996,17,2.9,1.0,2.4,86.0,6.8,1,6,65.9,...,False,True,False,True,True,False,False,False,False,True
997,S1997,20,3.0,2.6,1.3,61.9,6.5,5,9,64.4,...,False,False,True,False,False,False,False,True,False,True
998,S1998,24,5.4,4.1,1.1,100.0,7.6,0,1,69.7,...,False,True,False,False,False,False,False,False,False,False
999,S1999,19,4.3,2.9,1.9,89.4,7.1,2,8,74.9,...,False,False,True,False,False,False,False,False,False,False

In [12]:
data.isnull().sum()

student_id                              0
age                                     0
study_hours_per_day                     0
social_media_hours                      0
netflix_hours                           0
attendance_percentage                   0
sleep_hours                             0
exercise_frequency                      0
mental_health_rating                    0
exam_score                              0
gender_Male                             0
gender_Other                            0
part_time_job_Yes                       0
diet_quality_Good                       0
diet_quality_Poor                       0
parental_education_level_High School    0
parental_education_level_Master         0
parental_education_level_Unknown        0
internet_quality_Good                   0
internet_quality_Poor                   0
extracurricular_participation_Yes       0
dtype: int64

In [13]:
x=data.drop(["student_id","exam_score"],axis=1)
y=data["exam_score"]

In [14]:
x

,age,study_hours_per_day,social_media_hours,netflix_hours,attendance_percentage,sleep_hours,exercise_frequency,mental_health_rating,gender_Male,gender_Other,part_time_job_Yes,diet_quality_Good,diet_quality_Poor,parental_education_level_High School,parental_education_level_Master,parental_education_level_Unknown,internet_quality_Good,internet_quality_Poor,extracurricular_participation_Yes
0,23,0.0,1.2,1.1,85.0,8.0,6,8,False,False,False,False,False,False,True,False,False,False,True
1,20,6.9,2.8,2.3,97.3,4.6,6,8,False,False,False,True,False,True,False,False,False,False,False
2,21,1.4,3.1,1.3,94.8,8.0,1,1,True,False,False,False,True,True,False,False,False,True,False
3,23,1.0,3.9,1.0,71.0,9.2,4,1,False,False,False,False,True,False,True,False,True,False,True
4,19,5.0,4.4,0.5,90.9,4.9,3,1,False,False,False,False,False,False,True,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,21,2.6,0.5,1.6,77.0,7.5,2,6,False,False,False,False,False,True,False,False,True,False,True
996,17,2.9,1.0,2.4,86.0,6.8,1,6,False,False,True,False,True,True,False,False,False,False,True
997,20,3.0,2.6,1.3,61.9,6.5,5,9,True,False,False,True,False,False,False,False,True,False,True
998,24,5.4,4.1,1.1,100.0,7.6,0,1,True,False,True,False,False,False,False,False,False,False,False
999,19,4.3,2.9,1.9,89.4,7.1,2,8,False,False,False,True,False,False,False,False,False,False,False

In [15]:
y

0       56.2
1      100.0
2       34.3
3       26.8
4       66.4
       ...
995     76.1
996     65.9
997     64.4
998     69.7
999     74.9
Name: exam_score, Length: 1000, dtype: float64

In [16]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42)

In [17]:
model=LinearRegression()

In [18]:
model.fit(x_train,y_train)

LinearRegression()

In [19]:
y_pred=model.predict(x_test)

In [20]:
print("The r2 score is",r2_score(y_test, y_pred))

The r2 score is 0.8967502640380203

In [ ]:
print("The r2 score is",r2_score(y_test, y_pred))